### ISSUE TITLE
Runtime increases at small error rates

### ISSUE THREAD

**Issue by kmeinerz** [oscarhiggott/PyMatching#15]
Hello Oscar,

thank you very much for this very nice MWPM implementation.

I ran some benchmarks on the 3D Toric code and noticed some strange runtime behavior. At really small error rates, the decoding time actually starts to increase. See the graph below.

![Runtime](https://user-images.githubusercontent.com/44750309/132407298-10acc58e-0b23-4735-b10d-105645e9bf22.png)

For benchmarking, I used a slightly modified version of the 3D Toric code example from the documentation.
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import hstack, kron, eye, csr_matrix, block_diag
from pymatching import Matching
import time

def repetition_code(n):
    """
    Parity check matrix of a repetition code with length n.
    """
    row_ind, col_ind = zip(*((i, j) for i in range(n) for j in (i, (i+1)%n)))
    data = np.ones(2*n, dtype=np.uint8)
    return csr_matrix((data, (row_ind, col_ind)))


def toric_code_x_stabilisers(L):
    """
    Sparse check matrix for the X stabilisers of a toric code with
    lattice size L, constructed as the hypergraph product of
    two repetition codes.
    """
    Hr = repetition_code(L)
    H = hstack(
            [kron(Hr, eye(Hr.shape[1])), kron(eye(Hr.shape[0]), Hr.T)],
            dtype=np.uint8
        )
    H.data = H.data % 2
    H.eliminate_zeros()
    return csr_matrix(H)


def num_decoding_failures_noisy_syndromes(H, logicals, p, q, num_trials, repetitions):
    matching = Matching(H, spacelike_weights=np.log((1-p)/p),
                repetitions=repetitions, timelike_weights=np.log((1-q)/q))
    num_stabilisers, num_qubits = H.shape
    runtime = 0
    for i in range(num_trials):
        noise_new = (np.random.rand(num_qubits, repetitions) < p).astype(np.uint8)
        noise_cumulative = (np.cumsum(noise_new, 1) % 2).astype(np.uint8)
        noise_total = noise_cumulative[:,-1]
        syndrome = H@noise_cumulative % 2
        syndrome_error = (np.random.rand(num_stabilisers, repetitions) < q).astype(np.uint8)
        syndrome_error[:,-1] = 0 # Perfect measurements in last round to ensure even parity
        noisy_syndrome = (syndrome + syndrome_error) % 2
        # Convert to difference syndrome
        noisy_syndrome[:,1:] = (noisy_syndrome[:,1:] - noisy_syndrome[:,0:-1]) % 2
        
        runtime -= time.time()
        correction = matching.decode(noisy_syndrome)
        runtime += time.time()

    return runtime

def toric_code_x_logicals(L):
    """
    Sparse binary matrix with each row corresponding to an X logical operator
    of a toric code with lattice size L. Constructed from the
    homology groups of the repetition codes using the Kunneth
    theorem.
    """
    H1 = csr_matrix(([1], ([0],[0])), shape=(1,L), dtype=np.uint8)
    H0 = csr_matrix(np.ones((1, L), dtype=np.uint8))
    x_logicals = block_diag([kron(H1, H0), kron(H0, H1)])
    x_logicals.data = x_logicals.data % 2
    x_logicals.eliminate_zeros()
    return csr_matrix(x_logicals)

num_trials = 5000
Ls = [31]
ps =np.geomspace(0.0001, 0.1, 10)
for L in Ls:
    print("Simulating L={}...".format(L))
    Hx = toric_code_x_stabilisers(L)
    logX = toric_code_x_logicals(L)
    runtimes = []
    for p in ps:
        print(p)
        runtime = num_decoding_failures_noisy_syndromes(Hx, logX, p, p, num_trials, L)
        runtimes.append(1000*runtime/num_trials)

    plt.semilogx(ps, runtimes, "o-", label = f"L = {L}")

plt.xlabel("error rate")
plt.ylabel("avg. runtime [ms]")
plt.legend()
plt.show()
```

What is the cause of this behavior and can it be avoided?

Thanks,
Kai

**Comment by oscarhiggott** [comment]
Hi Kai,

Thank your for bringing this to my attention and for the analysis. Although slightly counterintuitive, this is actually expected behaviour. As you increase _p_, while there are more defects (highlighted nodes), these defects are also closer together in the matching graph which reduces the complexity of the local Dijkstra search for any defect.

More concretely, suppose you set `num_neighbours=m` and that the syndrome has weight _c_ (there are _c_ defects). We'll also denote the number of nodes in the matching graph by _N_. Assuming the noise is homogeneous, we expect a subgraph with roughly <img src="https://render.githubusercontent.com/render/math?math=Nm/c\approx m/p"> nodes to contain _m_ defects. In local matching, a local Dijkstra search is performed starting at each defect, and each search halts once _m_ defects are found. Dijkstra's algorithm has complexity _O(x log(x))_ for a graph with _x_ nodes. Therefore, each local Dijkstra search has complexity _O(m/p log(m/p))_, and there are _O(pN)_ such searches. This leads to an overall runtime for the Dijkstra step of _O(Nm log(m/p))_, which is a monotonically _decreasing_ function of _p_, consistent with what you observe at error rates around 10^{-3}. The assumptions above don't hold for all error rates - for sufficiently small _p_ (e.g. 10^{-4} in your example) there are fewer than _m_ defects, and for sufficiently large _p_, the number of defects is no longer well approximated as being proportional to _pN_. But the behaviour you ask about at error rates of 10^{-3} can be explained by the above argument.

Of course the blossom algorithm step is a monotonically increasing function of _p_, but the dominant cost in the regime you mention is the local Dijkstra search. I added the runtime of local Dijkstra and the Blossom algorithm onto your plot to demonstrate this:
![compare_total_vs_dijkstra_vs_blossom_runtime_L=31](https://user-images.githubusercontent.com/29460323/132589319-b273a0f5-7e26-4348-96c1-f1678a61766e.png)

Note that at low _p_ and for sufficiently small _L_ you could use exact matching (setting `num_neighbours=None`). This method precomputes all the shortest paths, which uses memory and time quadratic in _N_ and can be prohibitively expensive even for L=31. However, once this is precomputed, the time per sample can be faster for small _p_, and is a monotonically increasing function of _p_. E.g. here are runtimes for L=21:
![compare_total_vs_dijkstra_vs_blossom_runtime_L=21](https://user-images.githubusercontent.com/29460323/132591493-a53aa8d0-e0b8-43d9-8efc-95d467461d8c.png)

I'd generally recommend just sticking to local matching though, given how memory intensive the exact matching option is for large _L_.

I hope this helps,

Oscar

**Comment by kmeinerz** [comment]
Thank you for the quick reply. This really clarifies the matter and is a great help for me.
I am closing the issue.
