### ISSUE TITLE
Feed in a large amount of experiment data for one time?

### ISSUE THREAD

**Issue by inmzhang123** [oscarhiggott/PyMatching#16]
For example, I get more than 500,000 stabilizer results after running a single QEC experiment or simulation repeatedly. I want to decode this large amount of data efficiently. In my implementation, I input one set of exp data into  a fixed matching for one time, which takes relatively long time to decode all 500,000 results. I wonder whether there is more efficient way to do this.
```
m = pymatching.Matching(graph)
for exp in exps:
   correction = m.decode(exp)
   results.append(correction)
```

**Comment by oscarhiggott** [comment]
I just ran a couple of tests for surface code circuits with the same dimensions as you and also get a decoding time of around 50 microseconds per sample with the default setting (using 1% circuit-level depolarising noise). That seems reasonable/expected to me so I don't think there is any unexpected behaviour. Since the circuits are small, it's a little faster to use exact matching by setting `num_neighbours=None` in `Matching.decode` (since this caches the shortest paths). That reduces the runtime to around 35 microseconds for me. There are further optimisations to MWPM that can be made, but if you need to reduce the runtime further you might want to use another algorithm, such as Union-Find. How much faster do you need it to be for your use case?

**Comment by oscarhiggott** [comment]
Revisiting this issue using `decode_batch` in PyMatching v2.1.0 (with the new blossom implementation) and running on a distance=3, rounds=3 [dataset](https://zenodo.org/record/6804040) from the Google surface code experiment. Running:

```
import os
import time
import stim
import pymatching

fullpath = os.path.join(experiment_path, "surface_code_bX_d3_r03_center_3_5")
dem = stim.DetectorErrorModel.from_file(os.path.join(fullpath, "pij_from_even_for_odd.dem"))
shots = stim.read_shot_data_file(path=os.path.join(fullpath, "detection_events.b8"), format="b8", num_measurements=0, num_detectors=dem.num_detectors, num_observables=0)
actual_observables = stim.read_shot_data_file(path=os.path.join(fullpath, "obs_flips_actual.01"), format="01", num_measurements=0, num_detectors=0, num_observables=1)
matching = pymatching.Matching.from_detector_error_model(dem)
t1 = time.time()
for i in range(10):
    predicted_observables = matching.decode_batch(shots)
t2 = time.time()
print(t2-t1)
```

where `fullpath` is the path to the `google_qec3v5_experiment_data` directory now takes 0.3 seconds on my M2 machine. I ran 10 loops since the dataset is 50k shots, not 500k.
