### ISSUE TITLE
Matching cannot be initialized for parity check matrix for 3D codes cannot 

### ISSUE THREAD

**Issue by ehua7365** [oscarhiggott/PyMatching#33]
When the parity check matrix for the X stabilizers of the 2x2 2D toric code is used to initialise a `Matching` object, the following error is returned in version  v0.7.0. It had previously worked in version v0.2.4 without any error.
```
import numpy as np
from pymatching import Matching
H = np.array([
    [1, 0, 1, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 1, 1, 0, 0],
    [1, 0, 1, 0, 0, 0, 1, 1],
    [0, 1, 0, 1, 0, 0, 1, 1]
], dtype=np.uint)
syndrome = np.array([
    0, 0, 0, 0
], dtype=np.uint)
matcher = Matching(H)
matcher.decode(syndrome)
```

The following error message is produced
```
File ~/Documents/bn3d/panqec/venv/lib/python3.8/site-packages/pymatching/matching.py:522, in Matching.load_from_check_matrix(self, H, spacelike_weights, error_probabilities, repetitions, timelike_weights, measurement_error_probabilities, **kwargs)
    520         v1 = H.indices[s] + H.shape[0] * t
    521         v2 = H.indices[e - 1] + H.shape[0] * t if e - s == 2 else next(iter(boundary))
--> 522         self.matching_graph.add_edge(v1, v2, {i}, weights[i],
    523                                      error_probabilities[i], error_probabilities[i] >= 0)
    524 for t in range(repetitions - 1):
    525     for i in range(H.shape[0]):

ValueError: Edge (0,2) already exists in the matching graph, but parallel edges are not supported. Consider merging parallel edges into a single edge instead.
```

Perhaps is it possible to have backwards compatibility?

**Comment by eren-guttentag** [comment]
Having what I think is the same problem trying to initialize a `Matching` object for the 17-qubit surface code.

```
import numpy as np
from pymatching import Matching
Hz = np.array([[0, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1]])
Matching(Hz)
```
And this produces exactly the same error message (but with edge (2,4)).

**Comment by oscarhiggott** [comment]
The reason for this issue is that parallel edges aren't currently supported in pymatching (for the check matrices you have both given, there are duplicated columns) although I will add support for parallel edges in a future version. You can fix the issue with the current version by either (1) keeping only the parallel edge with the smallest weight, or (2) merging parallel edges. (2) is probably the better option since the error mechanisms of parallel edges are indistinguishable. Suppose edges e1 and e2 are parallel and have probabilities p1 and p2. Assuming they represent independent error mechanisms, they can be merged into a single edge e3 with probability p3=p1*(1-p2)+p2*(1-p1) and corresponding edge weight w3=log((1-p3)/p3). More generally, if you have many parallel edges with probabilities given in some list `probabilities`, then you can use the following function to find the probability of the merged edge (the probability that an odd number of the independent parallel edge error mechanisms occurred):

```
import functools


def prob_odd_number_of_errors(probabilities: List[float]) -> float:
    return functools.reduce(lambda x, y: x * (1 - y) + y * (1 - x), probabilities, 0.0)
```

In a future pymatching version, I'll probably just use the smallest-weight parallel edge by default, but provide an option to merge edges. I'll leave this issue open until then.

**Comment by oscarhiggott** [comment]
This is now fixed and will be in the next release. There will be a `merge_strategies` argument when loading from check matrix or adding an edge, which can be used to determine how pymatching merges parallel edges (with options `"disallow"`, `"independent"`, `"smallest-weight"`, `"keep-original"` and `"replace"`).
